/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialBalanceRouteImport } from './routes/trial-balance'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfitLossRouteImport } from './routes/profit-loss'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as BalanceSheetRouteImport } from './routes/balance-sheet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TrialBalanceRoute = TrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitLossRoute = ProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceSheetRoute = BalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/ledger': typeof LedgerRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/ledger': typeof LedgerRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRoute
  '/ledger': typeof LedgerRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/inventory'
    | '/journal'
    | '/ledger'
    | '/profit-loss'
    | '/reports'
    | '/trial-balance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/inventory'
    | '/journal'
    | '/ledger'
    | '/profit-loss'
    | '/reports'
    | '/trial-balance'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dashboard'
    | '/expenses'
    | '/income'
    | '/inventory'
    | '/journal'
    | '/ledger'
    | '/profit-loss'
    | '/reports'
    | '/trial-balance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BalanceSheetRoute: typeof BalanceSheetRoute
  CashFlowRoute: typeof CashFlowRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
  InventoryRoute: typeof InventoryRoute
  JournalRoute: typeof JournalRoute
  LedgerRoute: typeof LedgerRoute
  ProfitLossRoute: typeof ProfitLossRoute
  ReportsRoute: typeof ReportsRoute
  TrialBalanceRoute: typeof TrialBalanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trial-balance': {
      id: '/trial-balance'
      path: '/trial-balance'
      fullPath: '/trial-balance'
      preLoaderRoute: typeof TrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-loss': {
      id: '/profit-loss'
      path: '/profit-loss'
      fullPath: '/profit-loss'
      preLoaderRoute: typeof ProfitLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-sheet': {
      id: '/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof BalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BalanceSheetRoute: BalanceSheetRoute,
  CashFlowRoute: CashFlowRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
  InventoryRoute: InventoryRoute,
  JournalRoute: JournalRoute,
  LedgerRoute: LedgerRoute,
  ProfitLossRoute: ProfitLossRoute,
  ReportsRoute: ReportsRoute,
  TrialBalanceRoute: TrialBalanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
